apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  abdelali.conf: |
    server{
      
      listen 3000;
      root /var/www/abdelali;
      index index.html abdelali.html ;

      location / {
       try_files $uri /index.html= 404;
      }
    
    }
