apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: host-volume
          - mountPath: /var/www/abdelali;
            name: host-volume
          - mountPath: /etc/nginx/conf.d
            name: configmap
      volumes:
        - name: host-volume
          hostPath:
            path: /home/abdelali/react-app # this the path on the worker node where your web site resie
        - name: configmap
          configMap:
             name: nginx-config
             items:
               - key: abdelali.conf
                 path: abdelali.conf


